language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

install: true

script: ./gradlew bootJar

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_ACCESS_TOKEN
  file: target/app.jar
  on:
    repo: TwigCodes/twig-discovery
    tags: true

after_deploy:
  - ./gradlew pushDocker
