spring:
  profiles:
    active: dev
  cloud.config.server:
    prefix: /config
    git:
      uri: ${CONFIG_GIT_REPO_URI:https://gitee.com/twigcodes/twig-config-files.git}
      username: ${CONFIG_GIT_USERNAME}
      password: ${CONFIG_GIT_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  boot.admin.context-path: /admin
  aop:
    proxy-target-class: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
---
spring:
  profiles: dev
logging:
  level:
    org.springframework: DEBUG
    org.springframework.cloud: DEBUG
    com.twigcodes.discovery: DEBUG
    com.netflix.discovery: DEBUG
---
spring:
  profiles: prod
logging:
  level:
    org.springframework: ERROR
    org.springframework.security: ERROR
    org.springframework.security.oauth2: ERROR
    org.springframework.cloud: ERROR
    com.twigcodes.discovery: ERROR
    com.netflix.discovery: ERROR
