spring:
  profiles:
    active: local
  cloud.config.server:
    prefix: /config
    git.uri: ${CONFIG_GIT_REPO_URI:https://github.com/TwigCodes/twig-config-files.git}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  boot.admin.context-path: /admin
  aop:
    proxy-target-class: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
---
spring:
  profiles: local
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false
logging:
  level:
    org.springframework: DEBUG
    org.springframework.cloud: 'OFF'
    com.twigcodes.discovery: DEBUG
    com.netflix.discovery: 'OFF'
---
spring:
  profiles: dev
logging:
  level:
    org.springframework: DEBUG
    org.springframework.cloud: DEBUG
    com.twigcodes.discovery: DEBUG
    com.netflix.discovery: DEBUG
---
spring:
  profiles: prod
logging:
  level:
    org.springframework: ERROR
    org.springframework.security: ERROR
    org.springframework.security.oauth2: ERROR
    org.springframework.cloud: ERROR
    com.twigcodes.discovery: ERROR
    com.netflix.discovery: ERROR
